### ISSUE TITLE
Endless requesting administrative privileges

### ISSUE THREAD

**Issue by TON14** [sgeraldes/LightmassConfiguration#1] opened 2018-09-22 09:22 UTC
Endless message "requesting administrative privileges"
UAC service is completely DISABLED in system.

solution: 
delete string "CALL :UAC" and run as Administrator.

**Comment by sgeraldes** [comment] 2018-09-22 15:02
What OS are you using? Any other clues as to why it is failing?

**Comment by sgeraldes** [comment] 2018-09-22 15:09
Can you tell me what's the output of running "net session" from :
1) command prompt (regular user)
2) command prompt (right click, run as administrator)

**Comment by sgeraldes** [comment] 2018-09-22 15:34
I committed (hopefully) a fix. 

I could not reproduce the problem in Windows 10 with UAC disabled (although there may be many ways, even undocumented to disable UAC) and not sure about your system specs or config, neither the error you are having, so I'm assuming. 

The Call to ":UAC" all it does is to check admin rights on the currently running session. 

If it doesn't detect admin, it calls another script with "cscript.exe" to elevate and re-run the batch file, and checks for admin rights again. It uses UAC.ShellExecute to run elevated. 

I'll discard you have a problem with UAC.ShellExecute by disabling the service, since it clearly fires up the vbs script giving you the loop. And I can also discard cscript.exe not been found or something with it as the problem for the same reason. 

Assuming the problem was with how admin detection was done (Net Sessions somehow giving false output on your system), I updated the script and changed the detection method for a more "robust" one using fsutil. Not sure if anything else is modified on your system and this is just assumption on my side, so let me know if it works.

I'll close the issue as solved until I have more information to dig into.

**Closed as completed** 2018-09-22 15:34 UTC
